# Placeholder content
llms:
  openrouter:
    provider: openrouter
    model: openai/gpt-3.5-turbo   # O probá mistralai/mixtral-8x7b, meta-llama, etc.
    temperature: 0.7
    max_tokens: 1024
    api_key: ${OPENROUTER_API_KEY}
    endpoint: https://openrouter.ai/api/v1/chat/completions

  gpt:
    provider: openai
    model: gpt-4o
    temperature: 0.7
    max_tokens: 1024
    api_key: ${OPENAI_API_KEY}
    endpoint: https://api.openai.com/v1/chat/completions

  claude:
    provider: anthropic
    model: claude-3-opus-20240229
    temperature: 0.6
    max_tokens: 1000
    api_key: ${ANTHROPIC_API_KEY}
    endpoint: https://api.anthropic.com/v1/messages

image_models:
  stable_diffusion:
    provider: automatic1111
    version: v1-5
    sampler: Euler
    steps: 20
    cfg_scale: 7.5
    endpoint: http://localhost:7860/sdapi/v1/txt2img

audio_models:
  tts:
    provider: elevenlabs
    voice: "Rachel"
    stability: 0.5
    similarity_boost: 0.75
    api_key: ${ELEVENLABS_API_KEY}
    endpoint: https://api.elevenlabs.io/v1/text-to-speech


llms:
  local_ollama:
    provider: ollama
    model: gemma:2b
    temperature: 0.7
    max_tokens: 512
    endpoint: http://localhost:11434/api/chat






